package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const validInstructions = `---
description: Reviews pull requests.
---

You review pull requests carefully.
`

func writeAgent(t *testing.T, name, instructions string) string {
	t.Helper()
	root := filepath.Join(t.TempDir(), name)
	if err := os.Mkdir(root, 0o755); err != nil {
		t.Fatal(err)
	}
	if instructions != "" {
		if err := os.WriteFile(filepath.Join(root, "instructions.md"), []byte(instructions), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

// TestFiveMinuteJourney is the literal first journey: an authored directory
// applies into both harnesses' native always-on files, defaulting the
// workspace to the agent directory and honoring an explicit one.
func TestFiveMinuteJourney(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)

	var stdout, stderr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "claude"}, &stdout, &stderr); code != 0 {
		t.Fatalf("apply exit %d\nstdout: %s\nstderr: %s", code, stdout.String(), stderr.String())
	}
	claudeMD, err := os.ReadFile(filepath.Join(agent, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(claudeMD), "<!-- Generated by tenon apply") {
		t.Fatalf("generated file must be visibly tool-owned: %q", claudeMD)
	}
	if !strings.Contains(string(claudeMD), "You review pull requests carefully.") {
		t.Fatalf("generated file must carry the body: %q", claudeMD)
	}
	if strings.Contains(string(claudeMD), "description:") {
		t.Fatalf("generated file must not carry frontmatter: %q", claudeMD)
	}

	workspace := t.TempDir()
	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"apply", agent, "--harness", "codex", "--workspace", workspace}, &stdout, &stderr); code != 0 {
		t.Fatalf("codex apply exit %d\nstderr: %s", code, stderr.String())
	}
	if _, err := os.Stat(filepath.Join(workspace, "AGENTS.md")); err != nil {
		t.Fatal("agent source must apply outside its own directory:", err)
	}
	if _, err := os.Stat(filepath.Join(agent, "AGENTS.md")); !os.IsNotExist(err) {
		t.Fatal("codex output must land in the selected workspace only")
	}
}

// TestValidateReportsApplyFailuresWithoutMutating proves validate/apply
// parity: identical stable identifiers, and no workspace mutation from
// either command on a failing project.
func TestValidateReportsApplyFailuresWithoutMutating(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	if err := os.Mkdir(filepath.Join(agent, "tools"), 0o755); err != nil {
		t.Fatal(err)
	}

	var validateOut, applyOut, stderr bytes.Buffer
	validateCode := run([]string{"validate", agent, "--harness", "claude", "--diagnostics", "jsonl"}, &validateOut, &stderr)
	applyCode := run([]string{"apply", agent, "--harness", "claude", "--diagnostics", "jsonl"}, &applyOut, &stderr)
	if validateCode == 0 || applyCode == 0 {
		t.Fatalf("both must fail: validate=%d apply=%d", validateCode, applyCode)
	}
	if validateOut.String() != applyOut.String() {
		t.Fatalf("validate and apply must report identical diagnostics:\n%s\n%s",
			validateOut.String(), applyOut.String())
	}
	if _, err := os.Stat(filepath.Join(agent, "CLAUDE.md")); !os.IsNotExist(err) {
		t.Fatal("a failing apply must not mutate the workspace")
	}
	if _, err := os.Stat(filepath.Join(agent, ".tenon")); !os.IsNotExist(err) {
		t.Fatal("a failing apply must not write state")
	}
}

// TestJSONLDiagnosticsAreParseable proves the machine-readable contract: one
// JSON object per line carrying the stable identifier, authored path, and
// rule.
func TestJSONLDiagnosticsAreParseable(t *testing.T) {
	agent := writeAgent(t, "my-agent", "no frontmatter\n")

	var stdout, stderr bytes.Buffer
	if code := run([]string{"validate", agent, "--harness", "codex", "--diagnostics", "jsonl"}, &stdout, &stderr); code == 0 {
		t.Fatal("expected validation failure")
	}
	lines := strings.Split(strings.TrimSpace(stdout.String()), "\n")
	if len(lines) == 0 || lines[0] == "" {
		t.Fatal("expected at least one JSONL diagnostic")
	}
	sawMissingFrontmatter := false
	for _, line := range lines {
		var d struct {
			ID       string `json:"id"`
			Severity string `json:"severity"`
			Path     string `json:"path"`
			Rule     string `json:"rule"`
		}
		if err := json.Unmarshal([]byte(line), &d); err != nil {
			t.Fatalf("line %q is not one JSON diagnostic: %v", line, err)
		}
		if d.ID == "" || d.Severity == "" || d.Path == "" || d.Rule == "" {
			t.Fatalf("diagnostic must carry id, severity, path, and rule: %q", line)
		}
		if d.ID == "instructions.frontmatter.missing" && d.Path == "instructions.md" {
			sawMissingFrontmatter = true
		}
	}
	if !sawMissingFrontmatter {
		t.Fatalf("expected instructions.frontmatter.missing at instructions.md, got %v", lines)
	}
}

func TestUnknownCommandAndHarnessAreRejected(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := run([]string{"deploy"}, &stdout, &stderr); code == 0 {
		t.Fatal("unknown command must fail")
	}
	agent := writeAgent(t, "my-agent", validInstructions)
	if code := run([]string{"apply", agent, "--harness", "cursor"}, &stdout, &stderr); code == 0 {
		t.Fatal("unknown harness must fail")
	}
}
