package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/alee792/tenon/internal/generated"
)

const validInstructions = `---
description: Reviews pull requests.
---

You review pull requests carefully.
`

func writeAgent(t *testing.T, name, instructions string) string {
	t.Helper()
	root := filepath.Join(t.TempDir(), name)
	if err := os.Mkdir(root, 0o755); err != nil {
		t.Fatal(err)
	}
	if instructions != "" {
		if err := os.WriteFile(filepath.Join(root, "instructions.md"), []byte(instructions), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

// TestFiveMinuteJourney is the literal first journey: an authored directory
// applies into both harnesses' native always-on files, defaulting the
// workspace to the agent directory and honoring an explicit one.
func TestFiveMinuteJourney(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)

	var stdout, stderr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "claude"}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("apply exit %d\nstdout: %s\nstderr: %s", code, stdout.String(), stderr.String())
	}
	claudeMD, err := os.ReadFile(filepath.Join(agent, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(claudeMD), "<!-- Generated by tenon apply") {
		t.Fatalf("generated file must be visibly tool-owned: %q", claudeMD)
	}
	if !strings.Contains(string(claudeMD), "You review pull requests carefully.") {
		t.Fatalf("generated file must carry the body: %q", claudeMD)
	}
	if strings.Contains(string(claudeMD), "description:") {
		t.Fatalf("generated file must not carry frontmatter: %q", claudeMD)
	}
	if _, err := os.Stat(filepath.Join(agent, ".mcp.json")); err != nil {
		t.Fatal("claude must receive the generated managed MCP server:", err)
	}

	workspace := t.TempDir()
	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"apply", agent, "--harness", "codex", "--workspace", workspace}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("codex apply exit %d\nstderr: %s", code, stderr.String())
	}
	if _, err := os.Stat(filepath.Join(workspace, "AGENTS.md")); err != nil {
		t.Fatal("agent source must apply outside its own directory:", err)
	}
	if _, err := os.Stat(filepath.Join(workspace, ".codex", "config.toml")); err != nil {
		t.Fatal("codex must receive the generated managed MCP server:", err)
	}
	if _, err := os.Stat(filepath.Join(agent, "AGENTS.md")); !os.IsNotExist(err) {
		t.Fatal("codex output must land in the selected workspace only")
	}
}

// TestValidateReportsApplyFailuresWithoutMutating proves validate/apply
// parity: identical stable identifiers, and no workspace mutation from
// either command on a failing project.
func TestValidateReportsApplyFailuresWithoutMutating(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	if err := os.Mkdir(filepath.Join(agent, "schedules"), 0o755); err != nil {
		t.Fatal(err)
	}

	var validateOut, applyOut, stderr bytes.Buffer
	validateCode := run([]string{"validate", agent, "--harness", "claude", "--diagnostics", "jsonl"}, nil, &validateOut, &stderr)
	applyCode := run([]string{"apply", agent, "--harness", "claude", "--diagnostics", "jsonl"}, nil, &applyOut, &stderr)
	if validateCode == 0 || applyCode == 0 {
		t.Fatalf("both must fail: validate=%d apply=%d", validateCode, applyCode)
	}
	if validateOut.String() != applyOut.String() {
		t.Fatalf("validate and apply must report identical diagnostics:\n%s\n%s",
			validateOut.String(), applyOut.String())
	}
	if _, err := os.Stat(filepath.Join(agent, "CLAUDE.md")); !os.IsNotExist(err) {
		t.Fatal("a failing apply must not mutate the workspace")
	}
	if _, err := os.Stat(filepath.Join(agent, ".tenon")); !os.IsNotExist(err) {
		t.Fatal("a failing apply must not write state")
	}
}

// TestJSONLDiagnosticsAreParseable proves the machine-readable contract: one
// JSON object per line carrying the stable identifier, authored path, and
// rule.
func TestJSONLDiagnosticsAreParseable(t *testing.T) {
	agent := writeAgent(t, "my-agent", "no frontmatter\n")

	var stdout, stderr bytes.Buffer
	if code := run([]string{"validate", agent, "--harness", "codex", "--diagnostics", "jsonl"}, nil, &stdout, &stderr); code == 0 {
		t.Fatal("expected validation failure")
	}
	lines := strings.Split(strings.TrimSpace(stdout.String()), "\n")
	if len(lines) == 0 || lines[0] == "" {
		t.Fatal("expected at least one JSONL diagnostic")
	}
	sawMissingFrontmatter := false
	for _, line := range lines {
		var d struct {
			ID       string `json:"id"`
			Severity string `json:"severity"`
			Path     string `json:"path"`
			Rule     string `json:"rule"`
		}
		if err := json.Unmarshal([]byte(line), &d); err != nil {
			t.Fatalf("line %q is not one JSON diagnostic: %v", line, err)
		}
		if d.ID == "" || d.Severity == "" || d.Path == "" || d.Rule == "" {
			t.Fatalf("diagnostic must carry id, severity, path, and rule: %q", line)
		}
		if d.ID == "instructions.frontmatter.missing" && d.Path == "instructions.md" {
			sawMissingFrontmatter = true
		}
	}
	if !sawMissingFrontmatter {
		t.Fatalf("expected instructions.frontmatter.missing at instructions.md, got %v", lines)
	}
}

const echoSkillMD = `---
name: echo
description: Echoes input back.
---

Run scripts/run.sh to echo.
`

const vendorSkillMD = `---
name: vendor
description: Uses vendor fields.
when_to_use: Testing vendor fields.
model: opus
allowed-tools: Bash Read
---

Body.
`

func writeFile(t *testing.T, root, rel string, content []byte, mode os.FileMode) {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, content, mode); err != nil {
		t.Fatal(err)
	}
}

// markedSkillMD is the expected generated SKILL.md: the authored source with
// exactly one marker line inserted after the closing frontmatter delimiter.
func markedSkillMD(t *testing.T, source string) string {
	t.Helper()
	i := strings.Index(source, "\n---\n")
	if i < 0 {
		t.Fatalf("no closing delimiter in %q", source)
	}
	i += len("\n---\n")
	return source[:i] + generated.Marker + "\n" + source[i:]
}

type testDiag struct {
	ID       string `json:"id"`
	Severity string `json:"severity"`
	Path     string `json:"path"`
	Rule     string `json:"rule"`
}

// parseDiagLines decodes the leading JSONL diagnostics from a command's
// stdout, ignoring the human summary lines that follow.
func parseDiagLines(t *testing.T, out string) []testDiag {
	t.Helper()
	var ds []testDiag
	for _, line := range strings.Split(out, "\n") {
		if !strings.HasPrefix(line, "{") {
			continue
		}
		var d testDiag
		if err := json.Unmarshal([]byte(line), &d); err != nil {
			t.Fatalf("line %q is not one JSON diagnostic: %v", line, err)
		}
		ds = append(ds, d)
	}
	return ds
}

func filterDiags(ds []testDiag, id string) []testDiag {
	var out []testDiag
	for _, d := range ds {
		if d.ID == id {
			out = append(out, d)
		}
	}
	return out
}

// TestSkillAppliesToBothHarnesses proves skill-compatibility acceptance 1:
// a standard skill with referenced and arbitrary nested resources appears in
// both native project skill directories byte-identical to source with
// executable intent preserved, and the generated SKILL.md differs from
// source by exactly the one inserted marker line.
func TestSkillAppliesToBothHarnesses(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	script := []byte("#!/bin/sh\necho \"$@\"\n")
	notes := []byte("# Notes\n")
	blob := []byte{0x00, 0x01, 0xfe, 0xff}
	writeFile(t, agent, "skills/echo/SKILL.md", []byte(echoSkillMD), 0o644)
	writeFile(t, agent, "skills/echo/scripts/run.sh", script, 0o755)
	writeFile(t, agent, "skills/echo/references/notes.md", notes, 0o644)
	writeFile(t, agent, "skills/echo/deep/nested/data.bin", blob, 0o644)

	wantSkillMD := markedSkillMD(t, echoSkillMD)
	check := func(harness, prefix string) {
		t.Helper()
		ws := t.TempDir()
		var stdout, stderr bytes.Buffer
		if code := run([]string{"apply", agent, "--harness", harness, "--workspace", ws}, nil, &stdout, &stderr); code != 0 {
			t.Fatalf("%s apply exit %d\nstderr: %s", harness, code, stderr.String())
		}
		got, err := os.ReadFile(filepath.Join(ws, prefix, "SKILL.md"))
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != wantSkillMD {
			t.Fatalf("%s SKILL.md = %q, want the source with one marker line %q", harness, got, wantSkillMD)
		}
		for rel, want := range map[string][]byte{
			"scripts/run.sh":       script,
			"references/notes.md":  notes,
			"deep/nested/data.bin": blob,
		} {
			got, err := os.ReadFile(filepath.Join(ws, prefix, rel))
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(got, want) {
				t.Fatalf("%s %s = %q, want byte-identical source %q", harness, rel, got, want)
			}
		}
		info, err := os.Stat(filepath.Join(ws, prefix, "scripts/run.sh"))
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode().Perm()&0o111 == 0 {
			t.Fatalf("%s script must stay executable: %v", harness, info.Mode())
		}
		info, err = os.Stat(filepath.Join(ws, prefix, "references/notes.md"))
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode().Perm()&0o111 != 0 {
			t.Fatalf("%s non-executable resource must stay non-executable: %v", harness, info.Mode())
		}
	}
	check("claude", ".claude/skills/echo")
	check("codex", ".agents/skills/echo")
}

// TestSkillExecutableBitChangesFingerprint proves skill-compatibility
// acceptance 2: a mode-only change to a skill resource is a source change.
func TestSkillExecutableBitChangesFingerprint(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "skills/echo/SKILL.md", []byte(echoSkillMD), 0o644)
	writeFile(t, agent, "skills/echo/scripts/run.sh", []byte("#!/bin/sh\n"), 0o644)

	fingerprint := func() string {
		t.Helper()
		var stdout, stderr bytes.Buffer
		if code := run([]string{"validate", agent, "--harness", "claude"}, nil, &stdout, &stderr); code != 0 {
			t.Fatalf("validate exit %d\nstderr: %s", code, stderr.String())
		}
		i := strings.Index(stdout.String(), "fingerprint ")
		if i < 0 {
			t.Fatalf("no fingerprint in %q", stdout.String())
		}
		return strings.TrimSuffix(strings.TrimSpace(stdout.String()[i+len("fingerprint "):]), ")")
	}
	before := fingerprint()
	if err := os.Chmod(filepath.Join(agent, "skills/echo/scripts/run.sh"), 0o755); err != nil {
		t.Fatal(err)
	}
	after := fingerprint()
	if before == after {
		t.Fatalf("flipping the source executable bit must change the fingerprint: %s", before)
	}
}

// TestSymlinkedSkillResourceFailsBeforeWriting proves skill-compatibility
// acceptance 3: symlinked resources fail validation and a failing apply
// writes nothing.
func TestSymlinkedSkillResourceFailsBeforeWriting(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "skills/echo/SKILL.md", []byte(echoSkillMD), 0o644)
	target := filepath.Join(t.TempDir(), "real.md")
	if err := os.WriteFile(target, []byte("real\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(target, filepath.Join(agent, "skills/echo/link.md")); err != nil {
		t.Fatal(err)
	}

	ws := t.TempDir()
	var stdout, stderr bytes.Buffer
	code := run([]string{"apply", agent, "--harness", "claude", "--workspace", ws, "--diagnostics", "jsonl"}, nil, &stdout, &stderr)
	if code == 0 {
		t.Fatal("a symlinked skill resource must fail apply")
	}
	if len(filterDiags(parseDiagLines(t, stdout.String()), "skill.resource.invalid")) == 0 {
		t.Fatalf("expected skill.resource.invalid, got %q", stdout.String())
	}
	entries, err := os.ReadDir(ws)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 0 {
		t.Fatalf("a failing apply must write nothing; found %v", entries)
	}
}

// TestVendorFieldsWarnForCodexOnly proves skill-compatibility acceptance 4:
// recognized Claude frontmatter survives both applies and produces one
// sorted field-level warning per field for Codex only, exiting zero.
func TestVendorFieldsWarnForCodexOnly(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "skills/vendor/SKILL.md", []byte(vendorSkillMD), 0o644)
	wantFields := []string{"allowed-tools", "model", "when_to_use"}

	requireCodexWarnings := func(out string) {
		t.Helper()
		warnings := filterDiags(parseDiagLines(t, out), "skill.vendor-field.not-honored")
		if len(warnings) != len(wantFields) {
			t.Fatalf("warnings = %+v, want one per field %v", warnings, wantFields)
		}
		for i, d := range warnings {
			if d.Severity != "warning" || d.Path != "skills/vendor/SKILL.md" {
				t.Fatalf("warning %d = %+v", i, d)
			}
			if !strings.Contains(d.Rule, "\""+wantFields[i]+"\"") || !strings.Contains(d.Rule, "codex") ||
				!strings.Contains(d.Rule, "copied unchanged") {
				t.Fatalf("warning %d must name field %q, the selected harness, and the passthrough: %+v",
					i, wantFields[i], d)
			}
		}
	}

	var stdout, stderr bytes.Buffer
	ws := t.TempDir()
	if code := run([]string{"apply", agent, "--harness", "codex", "--workspace", ws, "--diagnostics", "jsonl"}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("warnings alone must not fail apply: exit %d, %s", code, stdout.String())
	}
	requireCodexWarnings(stdout.String())
	if _, err := os.ReadFile(filepath.Join(ws, ".agents/skills/vendor/SKILL.md")); err != nil {
		t.Fatal("the warned skill must still apply:", err)
	}

	stdout.Reset()
	if code := run([]string{"validate", agent, "--harness", "codex", "--diagnostics", "jsonl"}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("warnings alone must not fail validate: exit %d, %s", code, stdout.String())
	}
	requireCodexWarnings(stdout.String())

	stdout.Reset()
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", t.TempDir(), "--diagnostics", "jsonl"}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("claude apply exit %d: %s", code, stdout.String())
	}
	if got := filterDiags(parseDiagLines(t, stdout.String()), "skill.vendor-field.not-honored"); len(got) != 0 {
		t.Fatalf("claude must not warn on its own documented fields: %+v", got)
	}
}

// TestOpenAIYAMLRoundTripsAndWarnsForClaudeOnly proves skill-compatibility
// acceptance 5: agents/openai.yaml survives both applies byte-for-byte and
// produces exactly one file-level warning for Claude only.
func TestOpenAIYAMLRoundTripsAndWarnsForClaudeOnly(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	yaml := []byte("interface:\n  display_name: Echo\n")
	writeFile(t, agent, "skills/echo/SKILL.md", []byte(echoSkillMD), 0o644)
	writeFile(t, agent, "skills/echo/agents/openai.yaml", yaml, 0o644)

	apply := func(harness, ws string) []testDiag {
		t.Helper()
		var stdout, stderr bytes.Buffer
		if code := run([]string{"apply", agent, "--harness", harness, "--workspace", ws, "--diagnostics", "jsonl"}, nil, &stdout, &stderr); code != 0 {
			t.Fatalf("%s apply exit %d: %s", harness, code, stdout.String())
		}
		return parseDiagLines(t, stdout.String())
	}

	claudeWS, codexWS := t.TempDir(), t.TempDir()
	claudeDiags := apply("claude", claudeWS)
	codexDiags := apply("codex", codexWS)

	for harness, full := range map[string]string{
		"claude": filepath.Join(claudeWS, ".claude/skills/echo/agents/openai.yaml"),
		"codex":  filepath.Join(codexWS, ".agents/skills/echo/agents/openai.yaml"),
	} {
		got, err := os.ReadFile(full)
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(got, yaml) {
			t.Fatalf("%s agents/openai.yaml = %q, want byte-identical source", harness, got)
		}
	}
	warnings := filterDiags(claudeDiags, "skill.vendor-file.not-honored")
	if len(warnings) != 1 || warnings[0].Severity != "warning" ||
		warnings[0].Path != "skills/echo/agents/openai.yaml" ||
		!strings.Contains(warnings[0].Rule, "copied unchanged") {
		t.Fatalf("claude must emit exactly one file-level warning: %+v", claudeDiags)
	}
	if got := filterDiags(codexDiags, "skill.vendor-file.not-honored"); len(got) != 0 {
		t.Fatalf("codex must not warn on its own documented file: %+v", got)
	}
}

// TestFlatSkillLayoutIsRejected proves skill-compatibility acceptance 6.
func TestFlatSkillLayoutIsRejected(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "skills/flat.md", []byte("flat skill\n"), 0o644)

	var stdout, stderr bytes.Buffer
	if code := run([]string{"validate", agent, "--harness", "claude", "--diagnostics", "jsonl"}, nil, &stdout, &stderr); code == 0 {
		t.Fatal("the flat skills/NAME.md layout must be rejected")
	}
	got := filterDiags(parseDiagLines(t, stdout.String()), "skill.entry.invalid")
	if len(got) != 1 || got[0].Path != "skills/flat.md" ||
		!strings.Contains(got[0].Rule, "skills/flat/SKILL.md") {
		t.Fatalf("expected the flat-layout diagnostic naming skills/flat/SKILL.md, got %+v", got)
	}
}

// validPluginJSON is a minimal manifest targeting the canonical Agent
// Plugins v1.0.0 schema.
func validPluginJSON(name string) string {
	return `{"$schema": "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json", "name": "` + name + `"}`
}

// TestPluginSkillCollisionParity proves that when a plugin skill collides
// with a root skill of the same name, the root skill's bytes win in both
// harnesses' generated output, and validate and apply report the identical
// collision warning (parity).
func TestPluginSkillCollisionParity(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	rootSkillMD := "---\nname: echo\ndescription: The root echo skill.\n---\n\nRoot body.\n"
	pluginSkillMD := "---\nname: echo\ndescription: A vendored echo skill.\n---\n\nPlugin body.\n"
	writeFile(t, agent, "skills/echo/SKILL.md", []byte(rootSkillMD), 0o644)
	writeFile(t, agent, "plugins/vendor-x/plugin.json", []byte(validPluginJSON("vendor-x")), 0o644)
	writeFile(t, agent, "plugins/vendor-x/skills/echo/SKILL.md", []byte(pluginSkillMD), 0o644)

	requireCollisionWarning := func(out string) {
		t.Helper()
		got := filterDiags(parseDiagLines(t, out), "plugin.skill.collision")
		if len(got) != 1 || got[0].Severity != "warning" || got[0].Path != "plugins/vendor-x/skills/echo" ||
			!strings.Contains(got[0].Rule, "skills/echo") {
			t.Fatalf("expected exactly one plugin.skill.collision naming both authored paths, got %+v", got)
		}
	}

	var validateOut, stderr bytes.Buffer
	if code := run([]string{"validate", agent, "--harness", "claude", "--diagnostics", "jsonl"}, nil, &validateOut, &stderr); code != 0 {
		t.Fatalf("a collision warning alone must not fail validate: exit %d, %s", code, validateOut.String())
	}
	requireCollisionWarning(validateOut.String())

	wantSkillMD := markedSkillMD(t, rootSkillMD)
	check := func(harness, prefix string) {
		t.Helper()
		ws := t.TempDir()
		var applyOut bytes.Buffer
		if code := run([]string{"apply", agent, "--harness", harness, "--workspace", ws, "--diagnostics", "jsonl"}, nil, &applyOut, &stderr); code != 0 {
			t.Fatalf("%s apply exit %d\nstdout: %s", harness, code, applyOut.String())
		}
		requireCollisionWarning(applyOut.String())
		got, err := os.ReadFile(filepath.Join(ws, prefix, "SKILL.md"))
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != wantSkillMD {
			t.Fatalf("%s SKILL.md = %q, want the root skill's bytes %q", harness, got, wantSkillMD)
		}
	}
	check("claude", ".claude/skills/echo")
	check("codex", ".agents/skills/echo")
}

// TestPluginSkillRoundTripsByteForByte proves plugin-vendored skill
// resources round-trip byte-for-byte like root skills, including the
// inserted SKILL.md ownership marker.
func TestPluginSkillRoundTripsByteForByte(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	script := []byte("#!/bin/sh\necho \"$@\"\n")
	writeFile(t, agent, "plugins/vendor-x/plugin.json", []byte(validPluginJSON("vendor-x")), 0o644)
	writeFile(t, agent, "plugins/vendor-x/skills/echo/SKILL.md", []byte(echoSkillMD), 0o644)
	writeFile(t, agent, "plugins/vendor-x/skills/echo/scripts/run.sh", script, 0o755)

	wantSkillMD := markedSkillMD(t, echoSkillMD)
	check := func(harness, prefix string) {
		t.Helper()
		ws := t.TempDir()
		var stdout, stderr bytes.Buffer
		if code := run([]string{"apply", agent, "--harness", harness, "--workspace", ws}, nil, &stdout, &stderr); code != 0 {
			t.Fatalf("%s apply exit %d\nstderr: %s", harness, code, stderr.String())
		}
		got, err := os.ReadFile(filepath.Join(ws, prefix, "SKILL.md"))
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != wantSkillMD {
			t.Fatalf("%s SKILL.md = %q, want the source with one marker line %q", harness, got, wantSkillMD)
		}
		gotScript, err := os.ReadFile(filepath.Join(ws, prefix, "scripts/run.sh"))
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(gotScript, script) {
			t.Fatalf("%s scripts/run.sh = %q, want byte-identical source %q", harness, gotScript, script)
		}
		info, err := os.Stat(filepath.Join(ws, prefix, "scripts/run.sh"))
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode().Perm()&0o111 == 0 {
			t.Fatalf("%s script must stay executable: %v", harness, info.Mode())
		}
	}
	// The destination uses the skill name, not the plugin storage path.
	check("claude", ".claude/skills/echo")
	check("codex", ".agents/skills/echo")
}

// TestValidateApplyWarningParity proves spec acceptance 12 for warnings:
// validate's structured diagnostics on a skill-warning project are exactly
// apply's, and both exit zero.
func TestValidateApplyWarningParity(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "skills/vendor/SKILL.md", []byte(vendorSkillMD), 0o644)

	var validateOut, applyOut, stderr bytes.Buffer
	validateCode := run([]string{"validate", agent, "--harness", "codex", "--diagnostics", "jsonl"}, nil, &validateOut, &stderr)
	applyCode := run([]string{"apply", agent, "--harness", "codex", "--workspace", t.TempDir(), "--diagnostics", "jsonl"}, nil, &applyOut, &stderr)
	if validateCode != 0 || applyCode != 0 {
		t.Fatalf("warnings alone must not fail: validate=%d apply=%d", validateCode, applyCode)
	}
	validateDiags := parseDiagLines(t, validateOut.String())
	applyDiags := parseDiagLines(t, applyOut.String())
	if len(validateDiags) == 0 {
		t.Fatalf("expected warning diagnostics, got %q", validateOut.String())
	}
	if !slices.Equal(validateDiags, applyDiags) {
		t.Fatalf("validate and apply must report identical diagnostics:\n%+v\n%+v", validateDiags, applyDiags)
	}
}

const subagentInstructionsWithEffort = `---
description: Reviews the diff for style and correctness.
effort: high
---

Review the diff carefully.

Flag anything unclear.
`

const subagentInstructionsWithoutEffort = `---
description: Reviews the diff for style and correctness.
---

Review the diff carefully.

Flag anything unclear.
`

const wantClaudeSubagentWithEffort = "---\n" +
	"name: code-reviewer\n" +
	"description: \"Reviews the diff for style and correctness.\"\n" +
	"effort: high\n" +
	"---\n\n" +
	"Review the diff carefully.\n\nFlag anything unclear.\n"

const wantClaudeSubagentWithoutEffort = "---\n" +
	"name: code-reviewer\n" +
	"description: \"Reviews the diff for style and correctness.\"\n" +
	"---\n\n" +
	"Review the diff carefully.\n\nFlag anything unclear.\n"

const wantCodexSubagentWithEffort = "name = \"code_reviewer\"\n" +
	"description = \"Reviews the diff for style and correctness.\"\n" +
	"model_reasoning_effort = \"high\"\n" +
	"developer_instructions = \"Review the diff carefully.\\n\\nFlag anything unclear.\"\n"

const wantCodexSubagentWithoutEffort = "name = \"code_reviewer\"\n" +
	"description = \"Reviews the diff for style and correctness.\"\n" +
	"developer_instructions = \"Review the diff carefully.\\n\\nFlag anything unclear.\"\n"

// TestSubagentAppliesToBothHarnessesAndEffortRefreshRemovesLine proves
// subagent acceptance: a subagent with description, high effort, and a
// multi-line body applies to both harnesses with exactly the specified
// native rendering; removing effort from source and reapplying refreshes
// the owned generated file, dropping the effort/model_reasoning_effort line
// entirely rather than emitting it empty.
func TestSubagentAppliesToBothHarnessesAndEffortRefreshRemovesLine(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "subagents/code-reviewer/instructions.md", []byte(subagentInstructionsWithEffort), 0o644)

	claudeWS, codexWS := t.TempDir(), t.TempDir()
	var stdout, stderr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", claudeWS}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("claude apply exit %d: %s", code, stderr.String())
	}
	if code := run([]string{"apply", agent, "--harness", "codex", "--workspace", codexWS}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("codex apply exit %d: %s", code, stderr.String())
	}

	claudePath := filepath.Join(claudeWS, ".claude/agents/code-reviewer.md")
	codexPath := filepath.Join(codexWS, ".codex/agents/code-reviewer.toml")
	got, err := os.ReadFile(claudePath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantClaudeSubagentWithEffort {
		t.Fatalf("claude subagent file = %q, want %q", got, wantClaudeSubagentWithEffort)
	}
	got, err = os.ReadFile(codexPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantCodexSubagentWithEffort {
		t.Fatalf("codex subagent file = %q, want %q", got, wantCodexSubagentWithEffort)
	}

	// Remove effort from source and reapply; ownership allows the refresh.
	writeFile(t, agent, "subagents/code-reviewer/instructions.md", []byte(subagentInstructionsWithoutEffort), 0o644)
	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", claudeWS}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("claude reapply exit %d: %s", code, stderr.String())
	}
	if code := run([]string{"apply", agent, "--harness", "codex", "--workspace", codexWS}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("codex reapply exit %d: %s", code, stderr.String())
	}
	got, err = os.ReadFile(claudePath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantClaudeSubagentWithoutEffort {
		t.Fatalf("claude subagent file after effort removal = %q, want %q", got, wantClaudeSubagentWithoutEffort)
	}
	got, err = os.ReadFile(codexPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantCodexSubagentWithoutEffort {
		t.Fatalf("codex subagent file after effort removal = %q, want %q", got, wantCodexSubagentWithoutEffort)
	}
}

// TestSubagentChildToolsDirectoryFailsApplyBeforeWriting proves a subagent
// directory carrying an extra tools/ entry is rejected — not ignored — and
// a failing apply writes nothing.
func TestSubagentChildToolsDirectoryFailsApplyBeforeWriting(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "subagents/reviewer/instructions.md", []byte(minimalSubagentInstructionsFor("reviewer")), 0o644)
	writeFile(t, agent, "subagents/reviewer/tools/helper.ts", []byte("export default {}\n"), 0o644)

	ws := t.TempDir()
	var stdout, stderr bytes.Buffer
	code := run([]string{"apply", agent, "--harness", "claude", "--workspace", ws, "--diagnostics", "jsonl"}, nil, &stdout, &stderr)
	if code == 0 {
		t.Fatal("a subagent with a tools/ child must fail apply")
	}
	got := filterDiags(parseDiagLines(t, stdout.String()), "subagent.child.unsupported")
	if len(got) == 0 {
		t.Fatalf("expected subagent.child.unsupported, got %q", stdout.String())
	}
	entries, err := os.ReadDir(ws)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 0 {
		t.Fatalf("a failing apply must write nothing; found %v", entries)
	}
}

// TestNestedSubagentsDirectoryFailsApplyBeforeWriting proves a subagent
// directory carrying a nested subagents/ entry is rejected the same way as
// any other unsupported child, and a failing apply writes nothing.
func TestNestedSubagentsDirectoryFailsApplyBeforeWriting(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "subagents/reviewer/instructions.md", []byte(minimalSubagentInstructionsFor("reviewer")), 0o644)
	writeFile(t, agent, "subagents/reviewer/subagents/nested/instructions.md", []byte(minimalSubagentInstructionsFor("nested")), 0o644)

	ws := t.TempDir()
	var stdout, stderr bytes.Buffer
	code := run([]string{"apply", agent, "--harness", "codex", "--workspace", ws, "--diagnostics", "jsonl"}, nil, &stdout, &stderr)
	if code == 0 {
		t.Fatal("a nested subagents/ directory must fail apply")
	}
	got := filterDiags(parseDiagLines(t, stdout.String()), "subagent.child.unsupported")
	if len(got) == 0 {
		t.Fatalf("expected subagent.child.unsupported, got %q", stdout.String())
	}
	entries, err := os.ReadDir(ws)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 0 {
		t.Fatalf("a failing apply must write nothing; found %v", entries)
	}
}

// TestDeletingSubagentPrunesGeneratedFile proves stale removal end-to-end
// for subagents: removing an authored subagent and reapplying deletes its
// previously generated native file for the applied harness.
func TestDeletingSubagentPrunesGeneratedFile(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "subagents/helper/instructions.md", []byte(minimalSubagentInstructionsFor("helper")), 0o644)

	ws := t.TempDir()
	var stdout, stderr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", ws}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("apply exit %d: %s", code, stderr.String())
	}
	generated := filepath.Join(ws, ".claude/agents/helper.md")
	if _, err := os.Stat(generated); err != nil {
		t.Fatal("expected the generated subagent file to exist:", err)
	}

	if err := os.RemoveAll(filepath.Join(agent, "subagents", "helper")); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", ws}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("reapply exit %d: %s", code, stderr.String())
	}
	if _, err := os.Stat(generated); !os.IsNotExist(err) {
		t.Fatalf("expected the stale generated subagent file to be pruned: %v", err)
	}
	if !strings.Contains(stdout.String(), "removed .claude/agents/helper.md") {
		t.Fatalf("expected the removal to be reported: %q", stdout.String())
	}
}

// TestValidateApplyParityOnSubagentError proves spec acceptance 12 for a
// subagent-error project: validate's structured diagnostics equal apply's,
// and neither mutates the workspace.
func TestValidateApplyParityOnSubagentError(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "subagents/reviewer/instructions.md", []byte(minimalSubagentInstructionsFor("reviewer")), 0o644)
	writeFile(t, agent, "subagents/reviewer/tools/helper.ts", []byte("export default {}\n"), 0o644)

	var validateOut, applyOut, stderr bytes.Buffer
	validateCode := run([]string{"validate", agent, "--harness", "claude", "--diagnostics", "jsonl"}, nil, &validateOut, &stderr)
	applyCode := run([]string{"apply", agent, "--harness", "claude", "--workspace", t.TempDir(), "--diagnostics", "jsonl"}, nil, &applyOut, &stderr)
	if validateCode == 0 || applyCode == 0 {
		t.Fatalf("both must fail: validate=%d apply=%d", validateCode, applyCode)
	}
	if validateOut.String() != applyOut.String() {
		t.Fatalf("validate and apply must report identical diagnostics:\n%s\n%s",
			validateOut.String(), applyOut.String())
	}
	validateDiags := parseDiagLines(t, validateOut.String())
	if len(filterDiags(validateDiags, "subagent.child.unsupported")) == 0 {
		t.Fatalf("expected subagent.child.unsupported, got %q", validateOut.String())
	}
}

func minimalSubagentInstructionsFor(desc string) string {
	return "---\ndescription: Subagent " + desc + ".\n---\n\nDo the " + desc + " task.\n"
}

func TestUnknownCommandAndHarnessAreRejected(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := run([]string{"deploy"}, nil, &stdout, &stderr); code == 0 {
		t.Fatal("unknown command must fail")
	}
	agent := writeAgent(t, "my-agent", validInstructions)
	if code := run([]string{"apply", agent, "--harness", "cursor"}, nil, &stdout, &stderr); code == 0 {
		t.Fatal("unknown harness must fail")
	}
}

// TestHarnessFilesApplyOnlyToTheirOwnHarness proves harness-specific files
// round-trip byte-for-byte only to their selected harness: a claude apply
// writes exactly harnesses/claude's files and never codex's, and vice versa,
// with executable intent preserved.
func TestHarnessFilesApplyOnlyToTheirOwnHarness(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	settings := []byte(`{"model":"opus"}`)
	hook := []byte("#!/bin/sh\necho pre\n")
	rules := []byte("# Codex rules\n")
	writeFile(t, agent, "harnesses/claude/.claude/settings.json", settings, 0o644)
	writeFile(t, agent, "harnesses/claude/.claude/hooks/pre.sh", hook, 0o755)
	writeFile(t, agent, "harnesses/codex/.codex/rules.md", rules, 0o644)

	claudeWS := t.TempDir()
	var stdout, stderr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", claudeWS}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("claude apply exit %d\nstderr: %s", code, stderr.String())
	}
	got, err := os.ReadFile(filepath.Join(claudeWS, ".claude", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, settings) {
		t.Fatalf(".claude/settings.json = %q, want byte-identical %q", got, settings)
	}
	info, err := os.Stat(filepath.Join(claudeWS, ".claude", "hooks", "pre.sh"))
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm()&0o111 == 0 {
		t.Fatalf(".claude/hooks/pre.sh must stay executable: %v", info.Mode())
	}
	if _, err := os.Stat(filepath.Join(claudeWS, ".codex")); !os.IsNotExist(err) {
		t.Fatal("a claude apply must not write codex's harness-specific files")
	}

	codexWS := t.TempDir()
	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"apply", agent, "--harness", "codex", "--workspace", codexWS}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("codex apply exit %d\nstderr: %s", code, stderr.String())
	}
	got, err = os.ReadFile(filepath.Join(codexWS, ".codex", "rules.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, rules) {
		t.Fatalf(".codex/rules.md = %q, want byte-identical %q", got, rules)
	}
	if _, err := os.Stat(filepath.Join(codexWS, ".claude")); !os.IsNotExist(err) {
		t.Fatal("a codex apply must not write claude's harness-specific files")
	}
}

// TestHarnessFilesReservedDestinationsFailBeforeWriting proves reserved
// tenon-owned destinations are refused, including a case-folded alias, and a
// failing apply writes nothing.
func TestHarnessFilesReservedDestinationsFailBeforeWriting(t *testing.T) {
	cases := map[string]string{
		"claude skills":      "harnesses/claude/.claude/skills/anything",
		"claude case-folded": "harnesses/claude/.claude/SKILLS/x",
		"codex config.toml":  "harnesses/codex/.codex/config.toml",
	}
	for name, path := range cases {
		t.Run(name, func(t *testing.T) {
			agent := writeAgent(t, "my-agent", validInstructions)
			writeFile(t, agent, path, []byte("x"), 0o644)

			ws := t.TempDir()
			var stdout, stderr bytes.Buffer
			code := run([]string{"apply", agent, "--harness", "claude", "--workspace", ws, "--diagnostics", "jsonl"}, nil, &stdout, &stderr)
			if code == 0 {
				t.Fatal("a reserved harness-file destination must fail apply")
			}
			if len(filterDiags(parseDiagLines(t, stdout.String()), "harnessfile.path.reserved")) == 0 {
				t.Fatalf("expected harnessfile.path.reserved, got %q", stdout.String())
			}
			entries, err := os.ReadDir(ws)
			if err != nil {
				t.Fatal(err)
			}
			if len(entries) != 0 {
				t.Fatalf("a failing apply must write nothing; found %v", entries)
			}
		})
	}
}

// TestHarnessFilesUnknownHarnessDirectoryFails proves an unrecognized
// immediate entry under harnesses/ fails with the stable unknown-harness
// identifier.
func TestHarnessFilesUnknownHarnessDirectoryFails(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "harnesses/cursor/rules.md", []byte("body\n"), 0o644)

	var stdout, stderr bytes.Buffer
	code := run([]string{"validate", agent, "--harness", "claude", "--diagnostics", "jsonl"}, nil, &stdout, &stderr)
	if code == 0 {
		t.Fatal("an unknown harnesses/ entry must fail validation")
	}
	if len(filterDiags(parseDiagLines(t, stdout.String()), "harnessfile.harness.unknown")) == 0 {
		t.Fatalf("expected harnessfile.harness.unknown, got %q", stdout.String())
	}
}

// TestHarnessFilesRefuseHandAuthoredWorkspaceFile proves apply's generic
// ownership machinery covers harness-specific destinations too: a
// hand-authored .claude/settings.json already in the workspace is refused
// with apply.conflict.unowned rather than overwritten.
func TestHarnessFilesRefuseHandAuthoredWorkspaceFile(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "harnesses/claude/.claude/settings.json", []byte(`{"model":"opus"}`), 0o644)

	ws := t.TempDir()
	writeFile(t, ws, ".claude/settings.json", []byte(`{"hand":"authored"}`), 0o644)

	var stdout, stderr bytes.Buffer
	code := run([]string{"apply", agent, "--harness", "claude", "--workspace", ws, "--diagnostics", "jsonl"}, nil, &stdout, &stderr)
	if code == 0 {
		t.Fatal("a hand-authored native file already in the workspace must refuse apply")
	}
	got := filterDiags(parseDiagLines(t, stdout.String()), "apply.conflict.unowned")
	if len(got) == 0 {
		t.Fatalf("expected apply.conflict.unowned, got %q", stdout.String())
	}
	current, err := os.ReadFile(filepath.Join(ws, ".claude", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}
	if string(current) != `{"hand":"authored"}` {
		t.Fatal("the hand-authored file must not be overwritten")
	}
}

// TestHarnessFilesValidateApplyParity proves spec acceptance 12 for a
// harness-file error project: validate's structured diagnostics equal
// apply's, and neither mutates the workspace.
func TestHarnessFilesValidateApplyParity(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "harnesses/claude/.claude/agents/anything", []byte("x"), 0o644)

	ws := t.TempDir()
	var validateOut, applyOut, stderr bytes.Buffer
	validateCode := run([]string{"validate", agent, "--harness", "claude", "--diagnostics", "jsonl"}, nil, &validateOut, &stderr)
	applyCode := run([]string{"apply", agent, "--harness", "claude", "--workspace", ws, "--diagnostics", "jsonl"}, nil, &applyOut, &stderr)
	if validateCode == 0 || applyCode == 0 {
		t.Fatalf("both must fail: validate=%d apply=%d", validateCode, applyCode)
	}
	if validateOut.String() != applyOut.String() {
		t.Fatalf("validate and apply must report identical diagnostics:\n%s\n%s",
			validateOut.String(), applyOut.String())
	}
	validateDiags := parseDiagLines(t, validateOut.String())
	if len(filterDiags(validateDiags, "harnessfile.path.reserved")) == 0 {
		t.Fatalf("expected harnessfile.path.reserved, got %q", validateOut.String())
	}
	entries, err := os.ReadDir(ws)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 0 {
		t.Fatalf("a failing apply must write nothing; found %v", entries)
	}
}

// wantMCPJSON is the exact generated .mcp.json for one agent source and
// workspace: Claude's project MCP configuration carrying only the managed
// stdio server, pretty-printed with two-space indent and a trailing newline.
func wantMCPJSON(executable, source, workspace string) string {
	return `{
  "mcpServers": {
    "managed": {
      "args": [
        "mcp",
        "serve",
        "` + source + `",
        "--workspace",
        "` + workspace + `",
        "--harness",
        "claude"
      ],
      "command": "` + executable + `",
      "type": "stdio"
    }
  }
}
`
}

// wantCodexConfig is the exact generated .codex/config.toml: the managed
// server alone, required and pre-approved, under the ownership header.
func wantCodexConfig(executable, source, workspace string) string {
	return generated.TOMLHeader + `
[mcp_servers.managed]
command = "` + executable + `"
args = ["mcp", "serve", "` + source + `", "--workspace", "` + workspace + `", "--harness", "codex"]
required = true
default_tools_approval_mode = "approve"
`
}

func testExecutable(t *testing.T) string {
	t.Helper()
	executable, err := resolveExecutable()
	if err != nil {
		t.Fatal(err)
	}
	return executable
}

// TestApplyGeneratesTheManagedServerForBothHarnesses proves spec acceptance 2
// for the generated boundary: both harnesses receive the same managed MCP
// server, wired to the absolute agent source, workspace, and resolved tenon
// executable, and neither generated file carries a fingerprint, version, or
// other setup metadata.
func TestApplyGeneratesTheManagedServerForBothHarnesses(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	executable := testExecutable(t)

	claudeWS, codexWS := t.TempDir(), t.TempDir()
	var stdout, stderr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", claudeWS}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("claude apply exit %d\nstderr: %s", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "managed tools: echo via MCP; native harness tools remain unmanaged") {
		t.Fatalf("apply must report the managed tool surface: %q", stdout.String())
	}
	if !strings.Contains(stdout.String(), "wrote .mcp.json") {
		t.Fatalf("apply must report the generated .mcp.json: %q", stdout.String())
	}
	got, err := os.ReadFile(filepath.Join(claudeWS, ".mcp.json"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantMCPJSON(executable, agent, claudeWS) {
		t.Fatalf(".mcp.json =\n%s\nwant\n%s", got, wantMCPJSON(executable, agent, claudeWS))
	}

	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"apply", agent, "--harness", "codex", "--workspace", codexWS}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("codex apply exit %d\nstderr: %s", code, stderr.String())
	}
	got, err = os.ReadFile(filepath.Join(codexWS, ".codex", "config.toml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantCodexConfig(executable, agent, codexWS) {
		t.Fatalf(".codex/config.toml =\n%s\nwant\n%s", got, wantCodexConfig(executable, agent, codexWS))
	}
	for _, content := range []string{string(got), string(mustRead(t, filepath.Join(claudeWS, ".mcp.json")))} {
		for _, metadata := range []string{"sha256:", "fingerprint", "0.1.0-dev"} {
			if strings.Contains(content, metadata) {
				t.Fatalf("generated managed configuration must carry no setup metadata (%q): %s", metadata, content)
			}
		}
	}
}

func mustRead(t *testing.T, path string) []byte {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return content
}

// TestReapplyKeepsManagedConfigurationByteIdentical proves the generated
// managed configuration is deterministic for identical source and target.
func TestReapplyKeepsManagedConfigurationByteIdentical(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	for _, harness := range []string{"claude", "codex"} {
		t.Run(harness, func(t *testing.T) {
			ws := t.TempDir()
			path := filepath.Join(ws, ".mcp.json")
			if harness == "codex" {
				path = filepath.Join(ws, ".codex", "config.toml")
			}
			var stdout, stderr bytes.Buffer
			if code := run([]string{"apply", agent, "--harness", harness, "--workspace", ws}, nil, &stdout, &stderr); code != 0 {
				t.Fatalf("apply exit %d: %s", code, stderr.String())
			}
			first := mustRead(t, path)
			firstRecord := mustRead(t, filepath.Join(ws, ".tenon", "apply-"+harness+".json"))

			stdout.Reset()
			stderr.Reset()
			if code := run([]string{"apply", agent, "--harness", harness, "--workspace", ws}, nil, &stdout, &stderr); code != 0 {
				t.Fatalf("reapply exit %d: %s", code, stderr.String())
			}
			if !bytes.Equal(first, mustRead(t, path)) {
				t.Fatal("identical reapply must produce byte-identical managed configuration")
			}
			if !bytes.Equal(firstRecord, mustRead(t, filepath.Join(ws, ".tenon", "apply-"+harness+".json"))) {
				t.Fatal("identical reapply must produce a byte-identical apply record")
			}
		})
	}
}

// TestManagedServerFailsClosedOnUnappliedOrDriftedWorkspace proves the
// managed server refuses to serve setup nobody applied, or setup edited since
// apply, naming the cause and directing the operator to reapply.
func TestManagedServerFailsClosedOnUnappliedOrDriftedWorkspace(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)

	unapplied := t.TempDir()
	var stdout, stderr bytes.Buffer
	code := run([]string{"mcp", "serve", agent, "--harness", "claude", "--workspace", unapplied},
		bytes.NewBufferString(""), &stdout, &stderr)
	if code == 0 {
		t.Fatal("serving an un-applied workspace must fail closed")
	}
	if !strings.Contains(stderr.String(), "apply record") || !strings.Contains(stderr.String(), "tenon apply") {
		t.Fatalf("stderr must name the missing record and direct the operator: %q", stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("a refused session must write nothing to the protocol stream: %q", stdout.String())
	}

	applied := t.TempDir()
	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", applied}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("apply exit %d: %s", code, stderr.String())
	}
	if err := os.WriteFile(filepath.Join(applied, "CLAUDE.md"), []byte("hand edited\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	stdout.Reset()
	stderr.Reset()
	code = run([]string{"mcp", "serve", agent, "--harness", "claude", "--workspace", applied},
		bytes.NewBufferString(""), &stdout, &stderr)
	if code == 0 {
		t.Fatal("serving a workspace edited since apply must fail closed")
	}
	if !strings.Contains(stderr.String(), "CLAUDE.md") || !strings.Contains(stderr.String(), "tenon apply") {
		t.Fatalf("stderr must name the drifted file and direct the operator: %q", stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("a refused session must write nothing to the protocol stream: %q", stdout.String())
	}
}

// TestManagedServerServesTheAppliedAgent is the managed-boundary journey:
// after apply, the generated server initializes, advertises echo, returns
// bounded text through the boundary, and audits the call content-free.
func TestManagedServerServesTheAppliedAgent(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	ws := t.TempDir()
	var stdout, stderr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "codex", "--workspace", ws}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("apply exit %d: %s", code, stderr.String())
	}

	script := strings.Join([]string{
		`{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18"}}`,
		`{"jsonrpc":"2.0","method":"notifications/initialized"}`,
		`{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}`,
		`{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"echo","arguments":{"text":"CONSPICUOUS-ARGUMENT"}}}`,
	}, "\n") + "\n"
	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"mcp", "serve", agent, "--harness", "codex", "--workspace", ws},
		bytes.NewBufferString(script), &stdout, &stderr); code != 0 {
		t.Fatalf("mcp serve exit %d\nstderr: %s", code, stderr.String())
	}

	var responses []map[string]any
	for _, line := range strings.Split(strings.TrimSpace(stdout.String()), "\n") {
		var decoded map[string]any
		if err := json.Unmarshal([]byte(line), &decoded); err != nil {
			t.Fatalf("response %q is not JSON: %v", line, err)
		}
		responses = append(responses, decoded)
	}
	if len(responses) != 3 {
		t.Fatalf("got %d responses, want initialize, list, and call: %q", len(responses), stdout.String())
	}
	info := responses[0]["result"].(map[string]any)["serverInfo"].(map[string]any)
	if info["name"] != "tenon-managed" {
		t.Fatalf("serverInfo = %#v", info)
	}
	tools := responses[1]["result"].(map[string]any)["tools"].([]any)
	if len(tools) != 1 || tools[0].(map[string]any)["name"] != "echo" {
		t.Fatalf("managed surface = %#v", tools)
	}
	echo := responses[2]["result"].(map[string]any)
	if echo["isError"] != false || echo["structuredContent"].(map[string]any)["text"] != "CONSPICUOUS-ARGUMENT" {
		t.Fatalf("echo result = %#v", echo)
	}

	audit := stderr.String()
	if strings.Contains(audit, "CONSPICUOUS") {
		t.Fatalf("audit must stay content-free: %q", audit)
	}
	for _, outcome := range []string{"requested", "authorized", "completed"} {
		if !strings.Contains(audit, "outcome="+outcome) {
			t.Fatalf("audit is missing outcome=%s: %q", outcome, audit)
		}
	}
	if !strings.Contains(audit, "managed agent=my-agent tool=echo request=") {
		t.Fatalf("audit must name the served agent and tool: %q", audit)
	}
}

// TestManagedToolSurfaceReportsFrictionOptIn proves apply reports the opted-in
// built-in alongside echo.
func TestManagedToolSurfaceReportsFrictionOptIn(t *testing.T) {
	agent := writeAgent(t, "my-agent",
		"---\ndescription: Reviews pull requests.\nfriction-notes: true\n---\n\nYou review pull requests carefully.\n")
	var stdout, stderr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", t.TempDir()}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("apply exit %d: %s", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "managed tools: echo, record-friction via MCP; native harness tools remain unmanaged") {
		t.Fatalf("apply must report the opted-in managed surface: %q", stdout.String())
	}
}

// TestMCPSubcommandRejectsUnknownVerbs keeps the command surface closed.
func TestMCPSubcommandRejectsUnknownVerbs(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := run([]string{"mcp"}, nil, &stdout, &stderr); code == 0 {
		t.Fatal("bare mcp must fail")
	}
	if code := run([]string{"mcp", "connect"}, nil, &stdout, &stderr); code == 0 {
		t.Fatal("an unknown mcp subcommand must fail")
	}
}

// pluginMCPSchema is the canonical Agent Plugins v1.0.0 MCP schema
// identifier every plugin mcp.json must target.
const pluginMCPSchema = "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json"

// writePluginMCPAgent writes an agent carrying one vendored plugin whose
// mcp.json declares servers, plus the plugin-relative command and working
// directory the declaration addresses.
func writePluginMCPAgent(t *testing.T, servers string) string {
	t.Helper()
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "plugins/vendor-x/plugin.json",
		[]byte(`{"$schema": "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json", "name": "vendor-x"}`), 0o644)
	writeFile(t, agent, "plugins/vendor-x/bin/serve", []byte("#!/bin/sh\nexec cat\n"), 0o755)
	writeFile(t, agent, "plugins/vendor-x/work/.keep", nil, 0o644)
	writeFile(t, agent, "plugins/vendor-x/mcp.json",
		[]byte(`{"$schema": "`+pluginMCPSchema+`", "mcpServers": {`+servers+`}}`), 0o644)
	return agent
}

// pluginRealRoot is the plugin's absolute real root: the ${PLUGIN_ROOT} value
// and the containment boundary every plugin-relative path is proven against.
func pluginRealRoot(t *testing.T, agent string) string {
	t.Helper()
	root, err := filepath.EvalSymlinks(filepath.Join(agent, "plugins", "vendor-x"))
	if err != nil {
		t.Fatal(err)
	}
	return root
}

const pluginMCPServers = `
	"local": {"command": "./bin/serve", "args": ["--data=${PLUGIN_DATA}/db"], "env": {"MODE": "fast"}, "cwd": "${PLUGIN_ROOT}/work"},
	"remote": {"type": "streamable-http", "url": "https://example.com/mcp", "headers": {"X-Trace": "on"}}`

// TestPluginMCPServersApplyToBothHarnesses is the plugin-MCP journey: one
// vendored plugin's stdio and remote servers join the managed server in each
// harness's native project configuration, the stdio server keeps its declared
// working directory through Claude's directory-free format, and the private
// plugin data directory is created owner-only without ever becoming a
// tenon-owned generated file.
func TestPluginMCPServersApplyToBothHarnesses(t *testing.T) {
	agent := writePluginMCPAgent(t, pluginMCPServers)
	executable := testExecutable(t)
	root := pluginRealRoot(t, agent)

	claudeWS, codexWS := t.TempDir(), t.TempDir()
	claudeData := filepath.Join(claudeWS, ".tenon", "plugin-data", "my-agent", "vendor-x")
	codexData := filepath.Join(codexWS, ".tenon", "plugin-data", "my-agent", "vendor-x")

	var stdout, stderr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", claudeWS, "--diagnostics", "jsonl"}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("claude apply exit %d\nstdout: %s\nstderr: %s", code, stdout.String(), stderr.String())
	}
	wantClaude := `{
  "mcpServers": {
    "local": {
      "args": [
        "-C",
        "` + root + `/work",
        "--",
        "` + root + `/bin/serve",
        "--data=` + claudeData + `/db"
      ],
      "command": "/usr/bin/env",
      "env": {
        "MODE": "fast",
        "PLUGIN_DATA": "` + claudeData + `",
        "PLUGIN_ROOT": "` + root + `"
      },
      "type": "stdio"
    },
    "managed": {
      "args": [
        "mcp",
        "serve",
        "` + agent + `",
        "--workspace",
        "` + claudeWS + `",
        "--harness",
        "claude"
      ],
      "command": "` + executable + `",
      "type": "stdio"
    },
    "remote": {
      "headers": {
        "X-Trace": "on"
      },
      "type": "http",
      "url": "https://example.com/mcp"
    }
  }
}
`
	if got := string(mustRead(t, filepath.Join(claudeWS, ".mcp.json"))); got != wantClaude {
		t.Fatalf(".mcp.json =\n%s\nwant\n%s", got, wantClaude)
	}

	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"apply", agent, "--harness", "codex", "--workspace", codexWS, "--diagnostics", "jsonl"}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("codex apply exit %d\nstdout: %s\nstderr: %s", code, stdout.String(), stderr.String())
	}
	wantCodex := wantCodexConfig(executable, agent, codexWS) + `
[mcp_servers.local]
command = "` + root + `/bin/serve"
args = ["--data=` + codexData + `/db"]
cwd = "` + root + `/work"
env = { "MODE" = "fast", "PLUGIN_DATA" = "` + codexData + `", "PLUGIN_ROOT" = "` + root + `" }
required = false
default_tools_approval_mode = "prompt"

[mcp_servers.remote]
url = "https://example.com/mcp"
required = false
default_tools_approval_mode = "prompt"
`
	if got := string(mustRead(t, filepath.Join(codexWS, ".codex", "config.toml"))); got != wantCodex {
		t.Fatalf(".codex/config.toml =\n%s\nwant\n%s", got, wantCodex)
	}

	// The plugin data directory is private, persistent, and owner-only, and
	// it is never a tenon-owned generated file.
	for harness, data := range map[string]string{"claude": claudeData, "codex": codexData} {
		info, err := os.Stat(data)
		if err != nil {
			t.Fatalf("%s must create the plugin data directory: %v", harness, err)
		}
		if !info.IsDir() || info.Mode().Perm() != 0o700 {
			t.Fatalf("%s plugin data directory = %v, want an owner-only directory", harness, info.Mode())
		}
	}
	var record struct {
		Files map[string]any `json:"files"`
	}
	if err := json.Unmarshal(mustRead(t, filepath.Join(claudeWS, ".tenon", "apply-claude.json")), &record); err != nil {
		t.Fatal(err)
	}
	for path := range record.Files {
		if strings.Contains(path, "plugin-data") {
			t.Fatalf("the plugin data directory must never enter the apply record: %q", path)
		}
	}

	// Reapplying identical source is deterministic, and the surviving data
	// directory is not mistaken for drift.
	for harness, ws := range map[string]string{"claude": claudeWS, "codex": codexWS} {
		path := filepath.Join(ws, ".mcp.json")
		if harness == "codex" {
			path = filepath.Join(ws, ".codex", "config.toml")
		}
		before := mustRead(t, path)
		beforeRecord := mustRead(t, filepath.Join(ws, ".tenon", "apply-"+harness+".json"))
		stdout.Reset()
		stderr.Reset()
		if code := run([]string{"apply", agent, "--harness", harness, "--workspace", ws}, nil, &stdout, &stderr); code != 0 {
			t.Fatalf("%s reapply exit %d: %s", harness, code, stderr.String())
		}
		if !bytes.Equal(before, mustRead(t, path)) {
			t.Fatalf("%s reapply must produce byte-identical generated configuration", harness)
		}
		if !bytes.Equal(beforeRecord, mustRead(t, filepath.Join(ws, ".tenon", "apply-"+harness+".json"))) {
			t.Fatalf("%s reapply must produce a byte-identical apply record", harness)
		}
	}
}

// TestPluginMCPSurvivingPlaceholderSkipsClaudeOnly proves the per-harness
// protection: a value that still looks like a placeholder after portable
// expansion is skipped for Claude, which runs its own expansion pass, and
// generated unchanged for Codex, which does not — with identical diagnostics
// from validate and apply.
func TestPluginMCPSurvivingPlaceholderSkipsClaudeOnly(t *testing.T) {
	agent := writePluginMCPAgent(t,
		`"local": {"command": "./bin/serve", "args": ["--home=${HOME}"]}`)

	var applyOut, validateOut, stderr bytes.Buffer
	claudeWS := t.TempDir()
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", claudeWS, "--diagnostics", "jsonl"}, nil, &applyOut, &stderr); code != 0 {
		t.Fatalf("a per-harness skip must not fail apply: exit %d, %s", code, applyOut.String())
	}
	if code := run([]string{"validate", agent, "--harness", "claude", "--diagnostics", "jsonl"}, nil, &validateOut, &stderr); code != 0 {
		t.Fatalf("a per-harness skip must not fail validate: exit %d, %s", code, validateOut.String())
	}
	warnings := filterDiags(parseDiagLines(t, applyOut.String()), "plugin.mcp.claude-expansion")
	if len(warnings) != 1 || warnings[0].Severity != "warning" || warnings[0].Path != "plugins/vendor-x/mcp.json" {
		t.Fatalf("warnings = %+v, want one plugin.mcp.claude-expansion at the authored path", warnings)
	}
	if !strings.Contains(warnings[0].Rule, "${HOME}") || !strings.Contains(warnings[0].Rule, "claude") {
		t.Fatalf("the warning must name the surviving text and the selected harness: %+v", warnings[0])
	}
	if got := filterDiags(parseDiagLines(t, validateOut.String()), "plugin.mcp.claude-expansion"); len(got) != 1 || got[0] != warnings[0] {
		t.Fatalf("validate and apply must report identical diagnostics: %+v vs %+v", got, warnings)
	}
	claudeConfig := string(mustRead(t, filepath.Join(claudeWS, ".mcp.json")))
	if strings.Contains(claudeConfig, "${HOME}") || strings.Contains(claudeConfig, "local") {
		t.Fatalf("claude must not receive the skipped server: %s", claudeConfig)
	}
	if !strings.Contains(claudeConfig, "managed") {
		t.Fatalf("the managed server must survive a skipped plugin server: %s", claudeConfig)
	}

	codexWS := t.TempDir()
	var codexOut bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "codex", "--workspace", codexWS, "--diagnostics", "jsonl"}, nil, &codexOut, &stderr); code != 0 {
		t.Fatalf("codex apply exit %d: %s", code, codexOut.String())
	}
	if got := filterDiags(parseDiagLines(t, codexOut.String()), "plugin.mcp.claude-expansion"); len(got) != 0 {
		t.Fatalf("a harness without its own expansion pass must not be warned: %+v", got)
	}
	codexConfig := string(mustRead(t, filepath.Join(codexWS, ".codex", "config.toml")))
	if !strings.Contains(codexConfig, `args = ["--home=${HOME}"]`) {
		t.Fatalf("codex must receive the text unchanged: %s", codexConfig)
	}
}

// TestPluginMCPManagedNameIsReservedEndToEnd proves a plugin cannot shadow
// tenon's own managed server: the plugin server is skipped with a warning and
// the managed entry stays intact.
func TestPluginMCPManagedNameIsReservedEndToEnd(t *testing.T) {
	agent := writePluginMCPAgent(t, `"managed": {"command": "./bin/serve"}`)
	executable := testExecutable(t)

	ws := t.TempDir()
	var stdout, stderr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "claude", "--workspace", ws, "--diagnostics", "jsonl"}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("a reserved name must not fail apply: exit %d, %s", code, stdout.String())
	}
	warnings := filterDiags(parseDiagLines(t, stdout.String()), "plugin.mcp.server.collision")
	if len(warnings) != 1 || warnings[0].Path != "plugins/vendor-x/mcp.json" ||
		!strings.Contains(warnings[0].Rule, "never renamed") {
		t.Fatalf("warnings = %+v, want one reserved-name collision warning", warnings)
	}
	if got := string(mustRead(t, filepath.Join(ws, ".mcp.json"))); got != wantMCPJSON(executable, agent, ws) {
		t.Fatalf(".mcp.json =\n%s\nwant exactly the managed entry\n%s", got, wantMCPJSON(executable, agent, ws))
	}
}

// --- Connection authoring commands (ADR 0016) --------------------------------

// TestConnectionAddCreatesExactFile proves add validates offline and
// creates the exact expected file bytes, refusing to overwrite an existing
// connection.
func TestConnectionAddCreatesExactFile(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)

	var stdout, stderr bytes.Buffer
	code := run([]string{"connection", "add", agent, "catalog",
		"--url", "https://example.com/mcp", "--context", "Use for the catalog."}, nil, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("add exit %d\nstdout: %s\nstderr: %s", code, stdout.String(), stderr.String())
	}
	if !strings.Contains(stdout.String(), "run tenon apply") {
		t.Fatalf("expected a directive to run tenon apply: %s", stdout.String())
	}

	got := mustRead(t, filepath.Join(agent, "connections", "catalog.md"))
	want := "---\ntype: mcp\ntransport: streamable-http\nurl: https://example.com/mcp\n---\n\nUse for the catalog.\n"
	if string(got) != want {
		t.Fatalf("connections/catalog.md =\n%q\nwant\n%q", got, want)
	}

	stdout.Reset()
	stderr.Reset()
	code = run([]string{"connection", "add", agent, "catalog", "--url", "https://example.com/other"}, nil, &stdout, &stderr)
	if code == 0 {
		t.Fatal("add must refuse to overwrite an existing connection")
	}
	got2 := mustRead(t, filepath.Join(agent, "connections", "catalog.md"))
	if string(got2) != want {
		t.Fatalf("a refused overwrite must not change the existing file: %q", got2)
	}
}

// TestConnectionAddWithoutContextOmitsBody proves the body is omitted
// entirely, not emitted empty, when no --context is given.
func TestConnectionAddWithoutContextOmitsBody(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	var stdout, stderr bytes.Buffer
	if code := run([]string{"connection", "add", agent, "catalog", "--url", "https://example.com/mcp"}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("add exit %d: %s", code, stderr.String())
	}
	got := mustRead(t, filepath.Join(agent, "connections", "catalog.md"))
	want := "---\ntype: mcp\ntransport: streamable-http\nurl: https://example.com/mcp\n---\n"
	if string(got) != want {
		t.Fatalf("connections/catalog.md =\n%q\nwant\n%q", got, want)
	}
}

// TestConnectionAddPackageFlagFailsUnsupported proves add accepts
// --package/--capability but fails honestly rather than silently ignoring
// them or half-implementing the installed target form.
func TestConnectionAddPackageFlagFailsUnsupported(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	var stdout, stderr bytes.Buffer
	code := run([]string{"connection", "add", agent, "github",
		"--package", "github-mcp-server", "--capability", "github"}, nil, &stdout, &stderr)
	if code == 0 {
		t.Fatal("expected failure: installed targets are not supported yet")
	}
	if !strings.Contains(stderr.String(), "installed package targets are not supported yet; only remote streamable-http targets are available") {
		t.Fatalf("expected the exact honest diagnostic, got: %s", stderr.String())
	}
	if _, err := os.Stat(filepath.Join(agent, "connections", "github.md")); !os.IsNotExist(err) {
		t.Fatal("an unsupported add must not create a file")
	}
}

// TestConnectionAddRejectsInvalidURL and other offline validation failures
// must never create a file.
func TestConnectionAddRejectsInvalidURL(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	var stdout, stderr bytes.Buffer
	code := run([]string{"connection", "add", agent, "catalog", "--url", "http://example.com/mcp"}, nil, &stdout, &stderr)
	if code == 0 {
		t.Fatal("expected failure: plain http is never accepted")
	}
	if _, err := os.Stat(filepath.Join(agent, "connections")); !os.IsNotExist(err) {
		t.Fatal("a failed add must not create connections/")
	}
}

// TestConnectionStatusReportsConfiguredAndMalformed proves status lists
// healthy connections with their declared target and context presence, and
// reports a malformed connection with authored-path diagnostics and a
// nonzero result.
func TestConnectionStatusReportsConfiguredAndMalformed(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "connections/catalog.md",
		[]byte("---\ntype: mcp\ntransport: streamable-http\nurl: https://example.com/mcp\n---\n\nGuidance.\n"), 0o644)

	var stdout, stderr bytes.Buffer
	code := run([]string{"connection", "status", agent}, nil, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("status exit %d: %s", code, stderr.String())
	}
	out := stdout.String()
	if !strings.Contains(out, "catalog") || !strings.Contains(out, "configured") ||
		!strings.Contains(out, "runtime=unchecked") || !strings.Contains(out, "context present") {
		t.Fatalf("status output = %q", out)
	}

	// A second, malformed connection must be reported with its authored
	// path and make the result nonzero, without suppressing the first.
	writeFile(t, agent, "connections/broken.md", []byte("no frontmatter\n"), 0o644)
	stdout.Reset()
	stderr.Reset()
	code = run([]string{"connection", "status", agent}, nil, &stdout, &stderr)
	if code == 0 {
		t.Fatal("a malformed connection must make status nonzero")
	}
	if !strings.Contains(stdout.String(), "catalog") {
		t.Fatalf("the healthy connection must still be reported: %s", stdout.String())
	}
	if !strings.Contains(stderr.String(), "connections/broken.md") || !strings.Contains(stderr.String(), "connection.frontmatter.missing") {
		t.Fatalf("expected an authored-path diagnostic for the malformed connection: %s", stderr.String())
	}
}

// TestConnectionStatusByName proves the optional NAME argument filters to
// one connection and fails when it does not exist.
func TestConnectionStatusByName(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "connections/catalog.md",
		[]byte("---\ntype: mcp\ntransport: streamable-http\nurl: https://example.com/mcp\n---\n"), 0o644)
	writeFile(t, agent, "connections/search.md",
		[]byte("---\ntype: mcp\ntransport: streamable-http\nurl: https://search.example.com/mcp\n---\n"), 0o644)

	var stdout, stderr bytes.Buffer
	if code := run([]string{"connection", "status", agent, "catalog"}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("status exit %d: %s", code, stderr.String())
	}
	if strings.Contains(stdout.String(), "search") {
		t.Fatalf("expected only the named connection: %s", stdout.String())
	}

	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"connection", "status", agent, "missing"}, nil, &stdout, &stderr); code == 0 {
		t.Fatal("a nonexistent name must fail")
	}
}

// TestConnectionRemoveDeletesExactFileAndErrorsOnAbsent proves remove
// deletes exactly the named real file and fails without mutation when it is
// missing.
func TestConnectionRemoveDeletesExactFileAndErrorsOnAbsent(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "connections/catalog.md",
		[]byte("---\ntype: mcp\ntransport: streamable-http\nurl: https://example.com/mcp\n---\n"), 0o644)
	writeFile(t, agent, "connections/search.md",
		[]byte("---\ntype: mcp\ntransport: streamable-http\nurl: https://search.example.com/mcp\n---\n"), 0o644)

	var stdout, stderr bytes.Buffer
	if code := run([]string{"connection", "remove", agent, "catalog"}, nil, &stdout, &stderr); code != 0 {
		t.Fatalf("remove exit %d: %s", code, stderr.String())
	}
	if _, err := os.Stat(filepath.Join(agent, "connections", "catalog.md")); !os.IsNotExist(err) {
		t.Fatal("expected connections/catalog.md to be removed")
	}
	if _, err := os.Stat(filepath.Join(agent, "connections", "search.md")); err != nil {
		t.Fatal("remove must delete exactly the named file, not its siblings")
	}
	if !strings.Contains(stdout.String(), "run tenon apply") {
		t.Fatalf("expected a directive to run tenon apply: %s", stdout.String())
	}

	stdout.Reset()
	stderr.Reset()
	if code := run([]string{"connection", "remove", agent, "catalog"}, nil, &stdout, &stderr); code == 0 {
		t.Fatal("removing an absent connection must fail")
	}
}

// TestConnectionFullJourneyAddApplyClaude proves the literal author journey:
// add, then apply claude, produces the exact .mcp.json entry and the
// generated instructions connections section.
func TestConnectionFullJourneyAddApplyClaude(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)

	var addOut, addErr bytes.Buffer
	if code := run([]string{"connection", "add", agent, "catalog",
		"--url", "https://example.com/mcp", "--context", "Use for the catalog."}, nil, &addOut, &addErr); code != 0 {
		t.Fatalf("add exit: %s", addErr.String())
	}

	var applyOut, applyErr bytes.Buffer
	if code := run([]string{"apply", agent, "--harness", "claude"}, nil, &applyOut, &applyErr); code != 0 {
		t.Fatalf("apply exit: %s\n%s", applyOut.String(), applyErr.String())
	}

	mcpJSON := string(mustRead(t, filepath.Join(agent, ".mcp.json")))
	if !strings.Contains(mcpJSON, `"catalog"`) || !strings.Contains(mcpJSON, `"type": "http"`) ||
		!strings.Contains(mcpJSON, `"url": "https://example.com/mcp"`) {
		t.Fatalf(".mcp.json missing the connection entry: %s", mcpJSON)
	}
	if strings.Contains(mcpJSON, "headers") {
		t.Fatalf(".mcp.json must never carry a headers field for a connection: %s", mcpJSON)
	}
	claudeMD := string(mustRead(t, filepath.Join(agent, "CLAUDE.md")))
	if !strings.Contains(claudeMD, "## Native MCP connections") || !strings.Contains(claudeMD, "### catalog") ||
		!strings.Contains(claudeMD, "Use for the catalog.") {
		t.Fatalf("CLAUDE.md missing the connections section: %s", claudeMD)
	}
	if !strings.Contains(claudeMD, "owns native MCP startup") {
		t.Fatalf("CLAUDE.md missing the boundary sentence: %s", claudeMD)
	}
}

// TestConnectionValidateApplyParityOnConnectionError proves validate reports
// the same connection diagnostics as apply, without mutating the workspace.
func TestConnectionValidateApplyParityOnConnectionError(t *testing.T) {
	agent := writeAgent(t, "my-agent", validInstructions)
	writeFile(t, agent, "connections/catalog.md", []byte("no frontmatter\n"), 0o644)

	var validateOut, applyOut, stderr bytes.Buffer
	validateCode := run([]string{"validate", agent, "--harness", "claude", "--diagnostics", "jsonl"}, nil, &validateOut, &stderr)
	applyCode := run([]string{"apply", agent, "--harness", "claude", "--diagnostics", "jsonl"}, nil, &applyOut, &stderr)
	if validateCode == 0 || applyCode == 0 {
		t.Fatalf("both must fail: validate=%d apply=%d", validateCode, applyCode)
	}
	if validateOut.String() != applyOut.String() {
		t.Fatalf("validate and apply must report identical diagnostics:\n%s\n%s",
			validateOut.String(), applyOut.String())
	}
	validateDiags := parseDiagLines(t, validateOut.String())
	if len(filterDiags(validateDiags, "connection.frontmatter.missing")) == 0 {
		t.Fatalf("expected connection.frontmatter.missing, got %q", validateOut.String())
	}
	if _, err := os.Stat(filepath.Join(agent, "CLAUDE.md")); !os.IsNotExist(err) {
		t.Fatal("a failing apply must not mutate the workspace")
	}
}
