package stage

import "strings"

// entrypointScript renders the staged /opt/tenon/bin/agent-entrypoint. It is a
// minimal, deterministic POSIX shell script that fails closed: before handing
// off to the harness it verifies runtime identity (the staged tenon binary),
// the generated integration, and the source fingerprint against the artifact
// manifest by running `tenon stage verify`. Any verification failure exits
// nonzero without starting the harness.
//
// This slice's harness runtime is a documented placeholder: the harness
// executable is expected on PATH or in the base image (see
// harnessPlaceholderNote). After verification the entrypoint changes to the
// staged workspace and execs the harness. A --verify-only first argument runs
// verification alone and exits, which is the testable verify path.
func entrypointScript(harness string) []byte {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by tenon stage; do not edit. Fail-closed verification, then harness handoff.\n")
	b.WriteString("set -eu\n")
	b.WriteString("\n")
	b.WriteString("TENON=" + finalTenonBin + "\n")
	b.WriteString("ARTIFACT=" + finalArtifact + "\n")
	b.WriteString("\n")
	b.WriteString("if ! \"$TENON\" stage verify --artifact \"$ARTIFACT\"; then\n")
	b.WriteString("  echo 'tenon: staged filesystem verification failed; refusing to start' >&2\n")
	b.WriteString("  exit 1\n")
	b.WriteString("fi\n")
	b.WriteString("\n")
	b.WriteString("if [ \"${1:-}\" = \"--verify-only\" ]; then\n")
	b.WriteString("  exit 0\n")
	b.WriteString("fi\n")
	b.WriteString("\n")
	b.WriteString("cd " + finalWorkspace + "\n")
	b.WriteString("# The native harness runtime is not bundled in this slice; it is expected on PATH.\n")
	b.WriteString("exec " + harness + " \"$@\"\n")
	return []byte(b.String())
}
